### ISSUE TITLE
Error Log Spammed In Console

### ISSUE THREAD

**Issue by RageYT** [PeachesMLG/EpicSkyblock#2] opened 2019-07-12 01:27 UTC
This error keeps spamming in console, no matter what you do it still spams and I am 99.9% sure it's a issue in the code. I've deleted the plugin reinstalled it, deleted the config and deleted the world and yet the issue still occurs. 

https://pastebin.com/wmJ3EaXu

**Comment by Justsnoopy30** [comment] 2019-07-12 16:18
Cannot reproduce, I'm on paper 1.14.3, and I get no errors what-so-ever in the console. I see one difference, you're running spigot 1.12.2. Get off outdated versions and you might get better luck.

**Comment by RageYT** [comment] 2019-07-13 03:25
Uh, Spigot 1.12.2 is the most supported version as far as I know... 1.13+ are all unstable versions for servers and cause serious performance issues.

**Comment by PeachesMLG** [comment] 2019-07-13 11:39
Found the issue, will be fixed in the next version

**Closed by PeachesMLG** 2019-07-13 11:39 UTC
